import java.util.*;
public class Main{
    public static void main(String...args){
        try{
            int arr[]={0,1,2};
            System.out.println(arr[5]);
        }
        catch(ArithmeticException e){

            System.out.println("the error is that :"+e);
        }
        catch (ArrayIndexOutOfBoundsException e){
            System.out.println("the error is:"+ e);
        }
                finally{
            System.out.println("finally block is always executed");
        }
    }

output;
the error is:java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 3
finally block is always executed
